# Generated by Django 4.1.2 on 2023-03-09 06:17

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField()),
                ('category', models.CharField(max_length=500)),
                ('question_answer', djongo.models.fields.JSONField(blank=True, default={}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='App_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField()),
                ('package_name', models.TextField()),
                ('main_activity', models.TextField()),
                ('app_version', models.TextField()),
                ('md5', models.TextField()),
                ('sha256', models.TextField()),
                ('app_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('question_list', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=10)),
                ('last_name', models.TextField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(max_length=10, validators=[django.core.validators.RegexValidator('^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$', message='Password must contain at least one uppercase letter, one lowercase letter, one digit, one special character and minimum 8 length')])),
                ('role', models.CharField(default='user', max_length=50)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
