# Generated by Django 4.1.2 on 2023-03-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_info',
            name='app_category',
            field=models.TextField(default='CDAC Hyderabad'),
        ),
        migrations.AddField(
            model_name='app_info',
            name='tester',
            field=models.CharField(default='CDAC Hyderabad', max_length=255),
        ),
    ]
