# Generated by Django 4.1.2 on 2023-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_app_info_app_category_app_info_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_info',
            name='app_category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='app_info',
            name='tester',
            field=models.CharField(max_length=255),
        ),
    ]
