# Generated by Django 4.1.2 on 2023-03-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_app_info_app_category_alter_app_info_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Weightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField()),
                ('ownership_info', models.IntegerField()),
                ('company_related_info', models.IntegerField()),
                ('services_security', models.IntegerField()),
                ('privacy_policy', models.IntegerField()),
                ('data_related_info', models.IntegerField()),
                ('insecure_data_storage', models.IntegerField()),
                ('cryptography', models.IntegerField()),
                ('network_communication', models.IntegerField()),
                ('platform_interaction', models.IntegerField()),
                ('pgrm', models.IntegerField()),
            ],
        ),
    ]
