# Generated by Django 4.1.2 on 2023-03-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_category_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='md5',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='category_weightage',
            name='md5',
            field=models.TextField(default='default'),
        ),
    ]
