# Generated by Django 4.1.2 on 2023-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_answerdata_md5_category_weightage_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdata',
            name='md5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category_weightage',
            name='md5',
            field=models.TextField(),
        ),
    ]
